---
title: "Week3 Plotly - Funnel Data"
author: "SarahLynn"
date: "1/27/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Plot for Funnel Data

```{r load_clean2, echo=FALSE, results=FALSE, message=FALSE}
##load data
setwd("C:/Users/Sarah Lynn/Desktop/Self Study/jobs/VidAngel technical take home/DataSets/Wine Data")
wd_loc <- getwd()
wine_data <- read.csv(paste(wd_loc,"/WineData.csv",sep=""))


##load data
setwd("C:/Users/Sarah Lynn/Desktop/Self Study/Coursera DS JH - developing data products/Week 3 Interactive Plot Project Plotly")
wd_loc <- getwd()
funnel_data <- read.csv(paste(wd_loc,"/funneldata.csv",sep=""))


```


```{r funnel, echo=FALSE, message=FALSE}
library(plotly)

fig <- plot_ly(
    type = "funnel",
    name = 'Atlanta',
    y =names(funnel_data)[-1],
    x = as.numeric(funnel_data[2,-1]),
    orientation = "h",
    textposition = "inside",
    textinfo = "value+percent initial") 
fig <- fig %>%
  add_trace(
    type = "funnel",
    name = 'Dallas',
    orientation = "h",
    y = names(funnel_data)[-1],
    x = as.numeric(funnel_data[1,-1]),
    textposition = "inside",
    textinfo = "value+percent previous") 
fig <- fig %>%
  add_trace(
    type = "funnel",
    name = 'Phoenix',
    orientation = "h",
    y = names(funnel_data)[-1],
  x = as.numeric(funnel_data[3,-1]),
  textposition = "outside",
  textinfo = "value+percent total") 
fig <- fig %>%
  layout(yaxis = list(categoryarray = names(funnel_data)[-1]))

fig

```


## The End!
